settings:
  username: "Similarityoung"
  commit_msg: "Update README with recent activity"
  max_lines: 5
  readme_file: "./README.md"
  disabled_events:
    - "comments"
    - "wiki_create"
    - "added_member"
    - "new_star"
  ignored_repos:
    - "Similarityoung/Similarityoung"
    - "Similarityoung/simiclaw"
  line_prefix: "- "
messages:
  comments: "🗨️ Left a comment in {REPO}"
  push: "🚀 Pushed updates to {REPO}"
  issue_opened: "🐛 Opened an issue in {REPO}"
  issue_closed: "✅ Closed an issue in {REPO}"
  pr_opened: "🧩 Opened a PR in {REPO}"
  pr_closed: "📦 Closed a PR in {REPO}"
  pr_merged: "🎯 Merged a PR in {REPO}"
  changes_approved: "👍 Approved changes in {REPO}"
  changes_requested: "🛠️ Requested changes in {REPO}"
  new_release: "🏷️ Published a release in {REPO}"
